### ISSUE TITLE
Set bridge name manually

### ISSUE THREAD

**Issue by mikkonie** [bihealth/sodar-docker-compose#26]
Recreating the bridge name automatically during each deployment is generating warnings in monitoring. Might as well set it manually in the docker compose file. This should be doable as follows:

```
networks:
  sodar:
    driver_opts:
      com.docker.network.bridge.name: sodar-bridge
```
